name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker
      run: |
        sudo apt-get install -y docker-compose

    - name: build
      run: |
        docker-compose run linux-build && docker-compose run linux-run

